reddit:
    client_id: "mfFWD7VjBH7XlA"
    client_secret: "6OhJrfTYJT_KstZ_TjE0eWDEGKI"
subreddits:
    - name: "Animemes" 
      threshold: 500
      rclone: 
        - "toshokan:Stash/Animemes"
              
    - name: "Doujinshi"
      threshold: 750
      rclone: 
        - "toshokan:Doujinshi"
      filters:
         - tentacles
         - pregnant

    - name: "anime_irl"
      rclone: 
        - "toshokan:Stash/anime_irl"

    - name: "Popular"

global:
    threshold: 600
    filters:
        - tentacles
        - pregnant
        - Erwin
    rclone: 
        - "toshokan:Stash"
    limit: 25

