reddit:
    client_id: "mfFWD7VjBH7XlA"
    client_secret: "6OhJrfTYJT_KstZ_TjE0eWDEGKI"
subreddits:
    - name: "Animemes" 
      threshold: 500
      days: False
      repeats: False
      rclone: 
        - "toshokan:Animemes/"

global:
    threshold: 600
    filters:
        - tentacles
        - pregnant
        - Erwin
    rclone: 
        - "toshokan:Stash"
    limit: 25
    days: off

