reddit:
    client_id: "mfFWD7VjBH7XlA"
    client_secret: "6OhJrfTYJT_KstZ_TjE0eWDEGKI"
subreddits:
    - name: "Animemes" 
      threshold: 500
      limit: 250
      rclone: "toshokan:Stash/Animemes"
              
    - name: "Doujinshi"
      threshold: 750
      limit: 100
      rclone: "toshokan:Doujinshi"
      filters:
         - tentacles
         - pregnant

    - name: "anime_irl"
      threshold: 500
      rclone: "toshokan:Stash/anime_irl"

global:
    threshold: 500
    filters:
        - tentacles
        - pregnant
    rclone: "toshokan:Stash"
    limit: 1000

