reddit:
    client_id: "mfFWD7VjBH7XlA"
    client_secret: "6OhJrfTYJT_KstZ_TjE0eWDEGKI"
subreddits:
    - name: "Animemes" 
      threshold: 500
      days: True
      repeats: False
      rclone: 
        - "toshokan:Stash/Animemes"
              
    - name: "Doujinshi"
      threshold: 750
      rclone: 
        - "toshokan:Doujinshi"
      filters:
         - "tentacles"
         - "pregnant"
         - "[INCEST]"
         - "square panic"  

    - name: "anime_irl"
      repeats: True
      rclone: 
        - "toshokan:Stash/anime_irl"

    - name: "popular"
      limit: 200


global:
    threshold: 600
    filters:
        - tentacles
        - pregnant
        - Erwin
    rclone: 
        - "toshokan:Stash"
    limit: 25
    days: off

