reddit:
    client_id:
    client_secret:
subreddits:
    - name: "Animemes"
      threshold: 500
      days: False
      repeats: False
      limit: 200
      rclone: 
        - "toshokan:Animemes/"

global:
    threshold: 600
    filters:
        - Erwin
    rclone: 
        - "toshokan:Stash"
    limit: 25
    days: off

